# Generated by Django 5.1.4 on 2025-03-08 09:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stickers/')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=65)),
                ('status', models.CharField(choices=[('active', 'active'), ('close', 'close')], max_length=8)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Accountant', 'Accountant'), ('Auditor', 'Auditor'), ('Organizer', 'Organizer'), ('Supervisor', 'Supervisor')], max_length=25, null=True)),
                ('department', models.CharField(choices=[('CRM', 'CRM'), ('Halal Management', 'Halal Management'), ('Event Organizer', 'Event Organizer'), ('Accountancy', 'Accountancy')], max_length=25)),
                ('date_of_employment', models.DateField(auto_now_add=True)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('emergency_contacts', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('education', models.CharField(max_length=250)),
                ('university_college', models.CharField(max_length=250)),
                ('skills', models.TextField()),
                ('employment_type', models.CharField(choices=[('Full time', 'Full time')], default='Full time', max_length=15)),
                ('passport_number', models.CharField(max_length=150)),
                ('health_history', models.FileField(blank=True, null=True, upload_to='health_history_files/')),
                ('pay', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_personal', to='accounts.usersimple')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='HR.personal')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_given', to='HR.personal')),
                ('sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.sticker')),
            ],
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('waiting', 'waiting')], max_length=15)),
                ('type', models.CharField(choices=[('Paid vacation', 'Paid vacation'), ('Service note', 'Service note'), ('Maternity leave', 'Maternity leave'), ('Sick leave', 'Sick leave')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='vacation_request_document/')),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_status', to='HR.personal')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='HR.personal')),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('working', 'Working'), ('lunch', 'Lunch'), ('rest', 'Rest'), ('vacation', 'Vacation'), ('sick_leave', 'Sick_leave'), ('left_work', 'Left_work')], max_length=15)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('personal_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_status', to='HR.personal')),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='HR.personal')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='HR.visithistory')),
            ],
        ),
    ]
