
name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10.4-buster

    services:
      db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_DB: cooking_core
          POSTGRES_USER: cooking_core
          POSTGRES_PASSWORD: cooking_core

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r booking/req.txt

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          COOKING_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
          COOKING_CORE_SETTING_LOCAL_SETTINGS_PATH: './cooking_core/project/settings/templates/settings.github.py'
